version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grpc_network

  grpc_server:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg2://username:password@db:5432/dbname
    depends_on:
      - db
    ports:
      - "50051:50051"
    networks:
      - grpc_network
    volumes:
      - .:/app

networks:
  grpc_network:

volumes:
  postgres_data:
  app: